version: "3"

services:
  app: 
    build:
      context: .
    ports:
    - "5000:5000"
    volumes:
    - ./donate:/app
    # - /etc/resolv.conf:/etc/resolv.conf

    # command: >
    #   python donate_app.py